name = "moneylog"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "moneylog-prod"
database_id = "975415c6-c273-41fa-add5-ee36991c9dda"
